name: travelappflutter
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter_blurhash: ^0.6.0  # Update to the latest version
  file: ^6.1.2  # Update to the latest version
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.0.0
  cached_network_image_web: ^1.0.2
  flutter_svg: ^0.22.0
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  intl: ^0.17.0
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
